import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import ReduxServiceProvider from '@/_provider/ReduxServiceProvider';
import MainNavbar from '@/_ui/navbar/MainNavbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout( { children }: Readonly<{ children: React.ReactNode }> ) {
    return (
        <html lang = 'en' suppressHydrationWarning>
            <body className = { `antialiased` }>
                <ReduxServiceProvider>
                    <MainNavbar/>
                    { children }
                </ReduxServiceProvider>
            </body>
        </html>
    );
}
